In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import acquire
print("Scucess")

Scucess


# Pre Zillow
This notebook is used to prepare the zillow_wrangle.py function by performing basic operations to see things like value counts on columns, detect outliers, etc.

In [2]:
help(acquire)

Help on module acquire:

NAME
    acquire

FUNCTIONS
    columns_data(df)
        Takes in a data frame and returns the number of rows and percentage of rows missing per column
    
    get_connection(db, user='darden_1027', host='157.230.209.171', password='nIymKg6jJmIPe6gQxik57EkY3Fl9kmvl')
        Returns a formatted url with login credentials to access data on a SQL database.
    
    load_zillow_data()
        This function acquires the zillow dataset from a SQL Database.
        It returns the zillow dataset as a Pandas DataFrame.
        
        A local copy will be created as a csv file in the current directory for future use.
    
    row_data(df)
        Takes in a data frame and returns the range of columns with missing data, 
        what precentage of missing columns that represents,
        and how many rows have that number of missing columns
    
    summarize(df)
        Prints the basic summary statistics of a data frame

FILE
    c:\users\anthony\documents\data_scie

In [3]:
df = acquire.load_zillow_data()
df

C:\Users\anthony\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3337: DtypeWarning: Columns (69) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):


buildingclasstypeid  typeconstructiontypeid  storytypeid  \
0                      NaN                     NaN          NaN   
1                      NaN                     NaN          NaN   
2                      NaN                     NaN          NaN   
3                      NaN                     NaN          NaN   
4                      NaN                     NaN          NaN   
...                    ...                     ...          ...   
77376                  NaN                     NaN          NaN   
77377                  NaN                     NaN          NaN   
77378                  NaN                     NaN          NaN   
77379                  NaN                     NaN          NaN   
77380                  NaN                     NaN          NaN   

       propertylandusetypeid  heatingorsystemtypeid  architecturalstyletypeid  \
0                      261.0                    NaN                       NaN   
1                      261.0                    NaN                       NaN   
2                      261.0                    NaN                       NaN   
3                      261.0                    2.0                       NaN   
4                      266.0                    2.0                       NaN   
...                      ...                    ...                       ...   
77376                  261.0                    2.0                       NaN   
77377                  261.0                    NaN                       NaN   
77378                  261.0                    2.0                       NaN   
77379                  261.0                    2.0                       NaN   
77380                  261.0                    7.0                       NaN   

       airconditioningtypeid  parcelid       id  basementsqft  ...  \
0                        NaN  14297519  1727539           NaN  ...   
1                        NaN  17052889  1387261           NaN  ...   
2                        NaN  14186244    11677           NaN  ...   
3                        NaN  12177905  2288172           NaN  ...   
4                        1.0  10887214  1970746           NaN  ...   
...                      ...       ...      ...           ...  ...   
77376                    NaN  11000655   673515           NaN  ...   
77377                    NaN  17239384  2968375           NaN  ...   
77378                    1.0  12773139  1843709           NaN  ...   
77379                    NaN  12826780  1187175           NaN  ...   
77380                    NaN  13083743  2455685           NaN  ...   

       parcelid.1  logerror  transactiondate.1  airconditioningdesc  \
0        14297519  0.025595         2017-01-01                  NaN   
1        17052889  0.055619         2017-01-01                  NaN   
2        14186244  0.005383         2017-01-01                  NaN   
3        12177905 -0.103410         2017-01-01                  NaN   
4        10887214  0.006940         2017-01-01              Central   
...           ...       ...                ...                  ...   
77376    11000655  0.020615         2017-09-20                  NaN   
77377    17239384  0.013209         2017-09-21                  NaN   
77378    12773139  0.037129         2017-09-21              Central   
77379    12826780  0.007204         2017-09-25                  NaN   
77380    13083743 -0.197755         2018-05-25                  NaN   

       architecturalstyledesc  heatingorsystemdesc        propertylandusedesc  \
0                         NaN                  NaN  Single Family Residential   
1                         NaN                  NaN  Single Family Residential   
2                         NaN                  NaN  Single Family Residential   
3                         NaN              Central  Single Family Residential   
4                         NaN              Central                Condominium   
...                       ...                  ..

In [4]:
acquire.row_data(df)

num_cols_missing  num_rows  pct_cols_missing
0                 23         2          0.328571
1                 24        13          0.342857
2                 25        24          0.357143
3                 26        65          0.371429
4                 27       316          0.385714
5                 28       455          0.400000
6                 29      5270          0.414286
7                 30      3455          0.428571
8                 31      9891          0.442857
9                 32     12579          0.457143
10                33     14782          0.471429
11                34     13327          0.485714
12                35      5148          0.500000
13                36      5775          0.514286
14                37      3620          0.528571
15                38      1925          0.542857
16                39       285          0.557143
17                40       230          0.571429
18                41        29          0.585714
19                42        23          0.600000
20                43        28          0.614286
21                44        78          0.628571
22                45        50          0.642857
23                46         5          0.657143
24                47         3          0.671429
25                48         3          0.685714

In [5]:
acquire.columns_data(df)

columns  num_rows_missing  pct_rows_missing
0      buildingclasstypeid             77366          0.999806
1   typeconstructiontypeid             77159          0.997131
2              storytypeid             77331          0.999354
3    propertylandusetypeid                 0          0.000000
4    heatingorsystemtypeid             27941          0.361083
..                     ...               ...               ...
65     heatingorsystemdesc             27941          0.361083
66     propertylandusedesc                 0          0.000000
67               storydesc             77331          0.999354
68    typeconstructiondesc             77159          0.997131
69       buildingclassdesc             77366          0.999806

[70 rows x 3 columns]

In [6]:
df.poolcnt.value_counts()

1.0    16137
Name: poolcnt, dtype: int64

In [7]:
df.basementsqft.isnull().sum()


77331

In [8]:
df.storydesc.unique()

array([nan, 'Basement'], dtype=object)

In [9]:
df.heatingorsystemdesc.unique()

array([nan, 'Central', 'Floor/Wall', 'Forced air', 'Yes', 'None',
       'Radiant', 'Solar', 'Baseboard', 'Gravity', 'Heat Pump'],
      dtype=object)

In [10]:
print(df.fireplacecnt.isnull().sum())
print(df.fireplaceflag.isnull().sum())

69105
77209


In [11]:
((df['fireplaceflag'] == 1) == (df.fireplacecnt.isnull())).mean() * 100

10.917408666210052

In [12]:
df.hashottuborspa.unique()

array([nan,  1.])

In [13]:
df['propertylandusedesc'].loc[df['unitcnt'] == 1].value_counts()

Single Family Residential                   33734
Condominium                                 11494
Planned Unit Development                     1937
Mobile Home                                    53
Cooperative                                    29
Duplex (2 Units, Any Combination)              20
Residential General                            10
Commercial/Office/Residential Mixed Used        8
Townhouse                                       6
Triplex (3 Units, Any Combination)              2
Name: propertylandusedesc, dtype: int64

In [14]:
df['fips'].loc[df['unitcnt'] == 1].value_counts()

6037.0    47282
6059.0       10
6111.0        1
Name: fips, dtype: int64

In [51]:
def prep_zillow():
    '''
    Loads zillow data and then fliters it where propertylandusetypeid is 260, 261, 262, 263, 264, 265, 268, 275, 276, or 279.
    Drops unnecessary id columns and any duplicated columns.    
    Creates a has_ool column where poolcnt = 1.
    Creates a has_basement column where basementsqft > 0.
    Replaces nan values with 'none' for heatingorsystemdesc
    Replaces nan values with 0 for hashottuborspa. This was done because the only values were nan or 1
    Drops calculatedbathnbr, fullbathcnt,  columns 
    Drops columns where the percentage of missing data is over 25%
    Drop columns where the percentage of missing data is over 25%
    '''
    df = acquire.load_zillow_data()
    df = df[df.propertylandusetypeid.isin([260, 261, 262, 263, 264, 265, 268, 275, 276, 279])]
    df.drop(columns = ['buildingclasstypeid', 'typeconstructiontypeid', 'storytypeid',
                       'propertylandusetypeid', 'heatingorsystemtypeid', 'architecturalstyletypeid',
                       'airconditioningtypeid', 'id', 'parcelid'], inplace=True)
    df.drop(columns = [c for c in df.columns if c.endswith('.1')], inplace=True)
    df['has_pool'] = df['poolcnt'] == 1
    df['has_basement'] = df['basementsqft'] > 0
    df.heatingorsystemdesc.fillna('none')
    df.hashottuborspa.fillna(0)
    df.replace({True:1, False:0}, inplace = True)
    df = handle_missing_values(df, .6, .6)
    return df

In [25]:
def handle_missing_values(df, prop_required_column=.5, prop_required_row=.5):
    '''
    This function takes in a DataFrame (df), a minium for prop_required_column [0:1] with deafult of .5, 
    and a minimum value [0:1] for prop_required_row with a default of .5.
    
    It will first drop columns who's missing data is less than prop_required_column value.
    It will then drop the rows who's missing data is lower than the prop_required_row.
    '''
    columns_to_keep = []
    columns = df.columns
    for col in columns:   
        if df[col].notnull().sum()/df.shape[0] >= prop_required_column:
            columns_to_keep.append(col)
    df = df[columns_to_keep]
    df['row_to_keep'] = df.notnull().sum(axis=1)/df.shape[1] >= prop_required_row
    df = df.loc[df['row_to_keep'] == True]
    df.drop(columns= ['row_to_keep'], inplace = True)
    return df

In [52]:
df = prep_zillow()
df

C:\Users\anthony\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3417: DtypeWarning: Columns (69) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
<ipython-input-25-38dc43d33f77>:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['row_to_keep'] = df.notnull().sum(axis=1)/df.shape[1] >= prop_required_row


bathroomcnt  bedroomcnt  buildingqualitytypeid  calculatedbathnbr  \
0              3.5         4.0                    NaN                3.5   
1              1.0         2.0                    NaN                1.0   
2              2.0         3.0                    NaN                2.0   
3              3.0         4.0                    8.0                3.0   
6              3.0         4.0                    9.0                3.0   
...            ...         ...                    ...                ...   
77376          2.0         2.0                    6.0                2.0   
77377          2.0         4.0                    NaN                2.0   
77378          1.0         3.0                    4.0                1.0   
77379          2.0         3.0                    6.0                2.0   
77380          2.0         3.0                    4.0                2.0   

       calculatedfinishedsquarefeet  finishedsquarefeet12    fips  \
0                            3100.0                3100.0  6059.0   
1                            1465.0                1465.0  6111.0   
2                            1243.0                1243.0  6059.0   
3                            2376.0                2376.0  6037.0   
6                            2962.0                2962.0  6037.0   
...                             ...                   ...     ...   
77376                        1286.0                1286.0  6037.0   
77377                        1612.0                1612.0  6111.0   
77378                        1032.0                1032.0  6037.0   
77379                        1762.0                1762.0  6037.0   
77380                        1050.0                1050.0  6037.0   

       fullbathcnt    latitude    longitude  ...  assessmentyear  \
0              3.0  33634931.0 -117869207.0  ...          2016.0   
1              1.0  34449266.0 -119281531.0  ...          2016.0   
2              2.0  33886168.0 -117823170.0  ...          2016.0   
3              3.0  34245180.0 -118240722.0  ...          2016.0   
6              3.0  34145202.0 -118179824.0  ...          2016.0   
...            ...         ...          ...  ...             ...   
77376          2.0  34245368.0 -118282383.0  ...          2016.0   
77377          2.0  34300140.0 -118706327.0  ...          2016.0   
77378          1.0  34040895.0 -118038169.0  ...          2016.0   
77379          2.0  33937685.0 -117996709.0  ...          2016.0   
77380          2.0  34010864.0 -117900894.0  ...          2016.0   

      landtaxvaluedollarcnt taxamount  censustractandblock  transactiondate  \
0                  537569.0  11013.72         6.059063e+13       2017-01-01   
1                  376000.0   5672.48         6.111001e+13       2017-01-01   
2                  479489.0   6488.30         6.059022e+13       2017-01-01   
3                   36225.0   1777.51         6.037300e+13       2017-01-01   
6                  496619.0   9516.26         6.037461e+13       2017-01-01   
...                     ...       ...                  ...              ...   
77376              283704.0   4478.43         6.037101e+13       2017-09-20   
77377               16522.0   1107.48         6.111008e+13       2017-09-21   
77378               16749.0    876.43         6.037434e+13       2017-09-21   
77379              382000.0   6317.15         6.037503e+13       2017-09-25   
77380              182216.0   3345.78         6.037408e+13       2018-05-25   

       logerror  heatingorsystemdesc        propertylandusedesc  has_pool  \
0      0.025595                  NaN  Single Family Residential         0   
1      0.055619                  NaN  Single Family Residential         0   
2      0.005383                  NaN  Single Family Residential         1   
3     -0.103410              Central  Single Family Residential         1   
6     -0.001011              Central  Single Family Residential         1   
...         ...                  ... 

In [53]:
df.isnull().sum()

bathroomcnt                         0
bedroomcnt                          0
buildingqualitytypeid           19104
calculatedbathnbr                 197
calculatedfinishedsquarefeet      125
finishedsquarefeet12              332
fips                                0
fullbathcnt                       197
latitude                            0
longitude                           0
lotsizesquarefeet                 406
propertycountylandusecode           0
propertyzoningdesc              18970
rawcensustractandblock              0
regionidcity                     1034
regionidcounty                      0
regionidzip                        25
roomcnt                             0
unitcnt                         18992
yearbuilt                         157
structuretaxvaluedollarcnt         91
taxvaluedollarcnt                   1
assessmentyear                      0
landtaxvaluedollarcnt               2
taxamount                           4
censustractandblock               123
transactiond

In [35]:
df.propertyzoningdesc.unique()

array([nan, 'LCR110000*', 'PSR2', ..., 'LCRA7000-R', 'LCR1VV',
       'BFA15000*'], dtype=object)

In [42]:
df.buildingqualitytypeid.unique()

array([nan,  8.,  9.,  5.,  4.,  6.,  7., 10., 11.,  3., 12.,  2.,  1.])

In [46]:
df.propertyzoningdesc.unique()

array([nan, 'LCR110000*', 'PSR2', ..., 'LCRA7000-R', 'LCR1VV',
       'BFA15000*'], dtype=object)

In [47]:
df.heatingorsystemdesc.unique()

array([nan, 'Central', 'Floor/Wall', 'Forced air', 'Radiant', 'Solar',
       'None', 'Yes', 'Gravity', 'Baseboard'], dtype=object)

In [41]:
print(df['buildingqualitytypeid'].describe())
print(df['buildingqualitytypeid'].median())
print(df['buildingqualitytypeid'].mode())

count    33722.000000
mean         6.266947
std          1.716054
min          1.000000
25%          5.000000
50%          6.000000
75%          8.000000
max         12.000000
Name: buildingqualitytypeid, dtype: float64
6.0
0    6.0
dtype: float64


Additional columns to drop:
* heatingorsystemdesc
* unitcnt
* propertyzoningdesc
* finishedsquarefeet12